SELECT * FROM EMPLOYEE;

CREATE TABLE PRODUCT (
	PRODUCT_ID VARCHAR2(20) PRIMARY KEY,
	P_NAME VARCHAR2(20) NOT NULL,
	PRICE NUMBER(20) NOT NULL,
	DESCRIPTION VARCHAR2(20),
	STOCK NUMBER(10) NOT NULL
);

SELECT * FROM PRODUCT;

DELETE FROM PRODUCT WHERE P_NAME='cd';

UPDATE PRODUCT
SET P_NAME = '삼성티비', PRICE = 190000,
	DESCRIPTION ='x99',STOCK = 50
WHERE  PRODUCT_ID = 'nb_ss7';

ALTER TABLE PRODUCT
RENAME COLUMN PROUDCT_ID TO PRODUCT_ID;

ALTER TABLE PRODUCT DROP PRIMARY KEY;

ALTER TABLE PRODUCT ADD PRIMARY KEY(PRODUCT_ID);

<<<<<<< HEAD
SELECT * FROM PRODUCT WHERE P_NAME = 'nb_ama4';

SELECT * FROM PRODUCT;

SELECT * FROM PRODUCT WHERE P_NAME = 'nb_ama4';

SELECT * FROM PRODUCT;

